version: '2'
services:
  ide:
    image: ghcr.io/8ch9azbsfifz/sparksdr:latest
    command: bash -c "sleep 7 ; DISPLAY=novnc:0.0 /usr/local/bin/SparkSDR"
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  novnc:
    image: ghcr.io/8ch9azbsfifz/docker-novnc-single:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1600
      - DISPLAY_HEIGHT=968
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:

